# coding: utf-8

"""
    CrispHive Developer API

    Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "crisphive"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="CrispHive Developer API",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "CrispHive Developer API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (&#x60;Authorization: Bearer chsk_live_…&#x60;). The key prefix selects the data environment: &#x60;chsk_live_…&#x60; → production (live), &#x60;chsk_test_…&#x60; → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. &#x60;customers_view&#x60;, &#x60;job_create&#x60;, &#x60;team_manage&#x60;). A restricted key calling an endpoint outside its scope gets &#x60;403&#x60;. The full code list is the permission catalog (&#x60;GET /permission/modules&#x60; on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope &#x60;{ \&quot;error_code\&quot;: 0, \&quot;message\&quot;: \&quot;Success\&quot;, \&quot;data\&quot;: &lt;payload&gt; }&#x60;.
    """,  # noqa: E501
    package_data={"crisphive": ["py.typed"]},
)