# coding: utf-8

# flake8: noqa

"""
    CrispHive Developer API

    Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.1.0"

# import apis into sdk package
from crisphive.api.business_skill_api import BusinessSkillApi
from crisphive.api.customer_api import CustomerApi
from crisphive.api.job_request_business_api import JobRequestBusinessApi
from crisphive.api.job_types_api import JobTypesApi
from crisphive.api.service_area_api import ServiceAreaApi
from crisphive.api.technician_api import TechnicianApi
from crisphive.api.vehicle_api import VehicleApi

# import ApiClient
from crisphive.api_response import ApiResponse
from crisphive.api_client import ApiClient
from crisphive.configuration import Configuration
from crisphive.exceptions import OpenApiException
from crisphive.exceptions import ApiTypeError
from crisphive.exceptions import ApiValueError
from crisphive.exceptions import ApiKeyError
from crisphive.exceptions import ApiAttributeError
from crisphive.exceptions import ApiException

# import models into sdk package
from crisphive.models.create_customer200_response import CreateCustomer200Response
from crisphive.models.create_job_request200_response import CreateJobRequest200Response
from crisphive.models.customer import Customer
from crisphive.models.customer_address import CustomerAddress
from crisphive.models.customer_address_request import CustomerAddressRequest
from crisphive.models.customer_contact import CustomerContact
from crisphive.models.customer_create_request import CustomerCreateRequest
from crisphive.models.customer_create_response import CustomerCreateResponse
from crisphive.models.customer_list import CustomerList
from crisphive.models.customer_list_item import CustomerListItem
from crisphive.models.customer_profile import CustomerProfile
from crisphive.models.customer_spending import CustomerSpending
from crisphive.models.customer_tier_progress import CustomerTierProgress
from crisphive.models.customer_update_request import CustomerUpdateRequest
from crisphive.models.get_customer200_response import GetCustomer200Response
from crisphive.models.get_job_request200_response import GetJobRequest200Response
from crisphive.models.get_job_request_timeline200_response import GetJobRequestTimeline200Response
from crisphive.models.get_job_type200_response import GetJobType200Response
from crisphive.models.get_service_area200_response import GetServiceArea200Response
from crisphive.models.get_technician200_response import GetTechnician200Response
from crisphive.models.get_vehicle200_response import GetVehicle200Response
from crisphive.models.job_date import JobDate
from crisphive.models.job_date_business_range import JobDateBusinessRange
from crisphive.models.job_date_period import JobDatePeriod
from crisphive.models.job_date_period_entry import JobDatePeriodEntry
from crisphive.models.job_request import JobRequest
from crisphive.models.job_request_action_audit_by import JobRequestActionAuditBy
from crisphive.models.job_request_action_audit_entry import JobRequestActionAuditEntry
from crisphive.models.job_request_action_summary import JobRequestActionSummary
from crisphive.models.job_request_address_summary import JobRequestAddressSummary
from crisphive.models.job_request_archive_summary import JobRequestArchiveSummary
from crisphive.models.job_request_arrival_window import JobRequestArrivalWindow
from crisphive.models.job_request_assigned_vehicle import JobRequestAssignedVehicle
from crisphive.models.job_request_assignment_summary import JobRequestAssignmentSummary
from crisphive.models.job_request_booking_windows import JobRequestBookingWindows
from crisphive.models.job_request_business_time_range import JobRequestBusinessTimeRange
from crisphive.models.job_request_changes import JobRequestChanges
from crisphive.models.job_request_create_request import JobRequestCreateRequest
from crisphive.models.job_request_create_response import JobRequestCreateResponse
from crisphive.models.job_request_crew_member import JobRequestCrewMember
from crisphive.models.job_request_customer_summary import JobRequestCustomerSummary
from crisphive.models.job_request_day_windows import JobRequestDayWindows
from crisphive.models.job_request_job_date_business_range_request import JobRequestJobDateBusinessRangeRequest
from crisphive.models.job_request_job_date_period_request import JobRequestJobDatePeriodRequest
from crisphive.models.job_request_job_date_request import JobRequestJobDateRequest
from crisphive.models.job_request_list import JobRequestList
from crisphive.models.job_request_period import JobRequestPeriod
from crisphive.models.job_request_quote_summary import JobRequestQuoteSummary
from crisphive.models.job_request_rating_summary import JobRequestRatingSummary
from crisphive.models.job_request_schedule import JobRequestSchedule
from crisphive.models.job_request_session import JobRequestSession
from crisphive.models.job_request_skill_summary import JobRequestSkillSummary
from crisphive.models.job_request_status_summary import JobRequestStatusSummary
from crisphive.models.job_request_technician_info import JobRequestTechnicianInfo
from crisphive.models.job_request_timeline import JobRequestTimeline
from crisphive.models.job_request_timeline_action import JobRequestTimelineAction
from crisphive.models.job_request_timeline_event import JobRequestTimelineEvent
from crisphive.models.job_type import JobType
from crisphive.models.list_customers200_response import ListCustomers200Response
from crisphive.models.list_job_request_booking_windows200_response import ListJobRequestBookingWindows200Response
from crisphive.models.list_job_request_changes200_response import ListJobRequestChanges200Response
from crisphive.models.list_job_requests200_response import ListJobRequests200Response
from crisphive.models.list_job_types200_response import ListJobTypes200Response
from crisphive.models.list_service_areas200_response import ListServiceAreas200Response
from crisphive.models.list_skill_categories200_response import ListSkillCategories200Response
from crisphive.models.list_skills200_response import ListSkills200Response
from crisphive.models.list_skills_by_category200_response import ListSkillsByCategory200Response
from crisphive.models.list_technicians200_response import ListTechnicians200Response
from crisphive.models.list_vehicles200_response import ListVehicles200Response
from crisphive.models.model_date import ModelDate
from crisphive.models.pagination import Pagination
from crisphive.models.response_envelope import ResponseEnvelope
from crisphive.models.service_area import ServiceArea
from crisphive.models.service_area_list import ServiceAreaList
from crisphive.models.skill import Skill
from crisphive.models.skill_by_category_list import SkillByCategoryList
from crisphive.models.skill_category import SkillCategory
from crisphive.models.skill_category_list import SkillCategoryList
from crisphive.models.skill_list import SkillList
from crisphive.models.skill_summary import SkillSummary
from crisphive.models.technician import Technician
from crisphive.models.technician_address import TechnicianAddress
from crisphive.models.technician_lead_ref import TechnicianLeadRef
from crisphive.models.technician_list import TechnicianList
from crisphive.models.technician_service_area_ref import TechnicianServiceAreaRef
from crisphive.models.technician_status import TechnicianStatus
from crisphive.models.vehicle import Vehicle
from crisphive.models.vehicle_list import VehicleList
from crisphive.models.vehicle_owner import VehicleOwner
