# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_absence_alternative import JobRequestAbsenceAlternative
from crisphive.models.job_request_blocker import JobRequestBlocker
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsenceUnresolvedJob(BaseModel):
    """
    JobRequestAbsenceUnresolvedJob
    """ # noqa: E501
    alternatives: Optional[List[JobRequestAbsenceAlternative]] = Field(default=None, description="Preview, NO_QUALIFIED_TECH_FREE only: the relaxation ladder's priced options, cheapest constraint first — the FE's default is the first entry. Always an array; empty when even the ladder found nothing (and on commit rows). Each is a PROPOSAL until copied into commit.")
    blockers: Optional[List[JobRequestBlocker]] = Field(default=None, description="Engine diagnosis for the refused technicians (best-effort, may be absent).")
    customer_name: Optional[StrictStr] = Field(default=None, description="Customer name on the job.")
    var_date: Optional[date] = Field(default=None, description="Business-local calendar day (YYYY-MM-DD).", alias="date")
    end_at: Optional[datetime] = None
    job_id: Optional[StrictStr] = Field(default=None, description="UUID of the job.")
    message: Optional[StrictStr] = Field(default=None, description="Human-readable explanation (English).")
    priority: Optional[StrictStr] = Field(default=None, description="Priority (p0..p3).")
    reason_code: Optional[StrictStr] = Field(default=None, description="Why it stayed unresolved. EXTEND-ONLY — carry a default branch. NOT_COMMITTED appears on commit only (a row the caller left out).")
    short_code: Optional[StrictStr] = Field(default=None, description="Human-friendly short code.")
    start_at: Optional[datetime] = Field(default=None, description="The job's window (UTC) — unchanged, still on the absent technician.")
    __properties: ClassVar[List[str]] = ["alternatives", "blockers", "customer_name", "date", "end_at", "job_id", "message", "priority", "reason_code", "short_code", "start_at"]

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['p0', 'p1', 'p2', 'p3']):
            raise ValueError("must be one of enum values ('p0', 'p1', 'p2', 'p3')")
        return value

    @field_validator('reason_code')
    def reason_code_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NO_QUALIFIED_TECH_FREE', 'CREW_JOB_UNSUPPORTED', 'MULTIDAY_UNSUPPORTED', 'IN_PROGRESS', 'NOT_REASSIGNABLE', 'NOT_COMMITTED']):
            raise ValueError("must be one of enum values ('NO_QUALIFIED_TECH_FREE', 'CREW_JOB_UNSUPPORTED', 'MULTIDAY_UNSUPPORTED', 'IN_PROGRESS', 'NOT_REASSIGNABLE', 'NOT_COMMITTED')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceUnresolvedJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in alternatives (list)
        _items = []
        if self.alternatives:
            for _item_alternatives in self.alternatives:
                if _item_alternatives:
                    _items.append(_item_alternatives.to_dict())
            _dict['alternatives'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in blockers (list)
        _items = []
        if self.blockers:
            for _item_blockers in self.blockers:
                if _item_blockers:
                    _items.append(_item_blockers.to_dict())
            _dict['blockers'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceUnresolvedJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternatives": [JobRequestAbsenceAlternative.from_dict(_item) for _item in obj["alternatives"]] if obj.get("alternatives") is not None else None,
            "blockers": [JobRequestBlocker.from_dict(_item) for _item in obj["blockers"]] if obj.get("blockers") is not None else None,
            "customer_name": obj.get("customer_name"),
            "date": obj.get("date"),
            "end_at": obj.get("end_at"),
            "job_id": obj.get("job_id"),
            "message": obj.get("message"),
            "priority": obj.get("priority"),
            "reason_code": obj.get("reason_code"),
            "short_code": obj.get("short_code"),
            "start_at": obj.get("start_at")
        })
        return _obj


