# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsenceAlternativeCost(BaseModel):
    """
    JobRequestAbsenceAlternativeCost
    """ # noqa: E501
    customer_renotified: Optional[StrictBool] = Field(default=None, description="The customer is told a NEW appointment time (job_rescheduled), not only a new technician name.")
    day_offset: Optional[StrictInt] = Field(default=None, description="Calendar days between the original and the new window's business-local dates (0 = same day / reassign).")
    distance_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The technician's own driving distance to the site in km. ABSENT when the engine had no route — never render \"0 km\".")
    outside_service_area: Optional[StrictBool] = Field(default=None, description="The technician is not assigned to any service area covering the job (sent out of zone).")
    sla_breached: Optional[StrictBool] = Field(default=None, description="The job carries an SLA deadline and the new window ends after it.")
    travel_minutes: Optional[StrictInt] = Field(default=None, description="The technician's one-way commute estimate in minutes (rounded up). Absent when unknown.")
    window_moved: Optional[StrictBool] = Field(default=None, description="The customer's appointment changes (reschedule kinds).")
    __properties: ClassVar[List[str]] = ["customer_renotified", "day_offset", "distance_km", "outside_service_area", "sla_breached", "travel_minutes", "window_moved"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceAlternativeCost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceAlternativeCost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "customer_renotified": obj.get("customer_renotified"),
            "day_offset": obj.get("day_offset"),
            "distance_km": obj.get("distance_km"),
            "outside_service_area": obj.get("outside_service_area"),
            "sla_breached": obj.get("sla_breached"),
            "travel_minutes": obj.get("travel_minutes"),
            "window_moved": obj.get("window_moved")
        })
        return _obj


