# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_session import JobRequestSession
from crisphive.models.job_request_time_segments_business_time import JobRequestTimeSegmentsBusinessTime
from crisphive.models.job_request_time_segments_worker import JobRequestTimeSegmentsWorker
from typing import Optional, Set
from typing_extensions import Self

class JobRequestTimeSegmentsSlot(BaseModel):
    """
    JobRequestTimeSegmentsSlot
    """ # noqa: E501
    available_workers: Optional[List[JobRequestTimeSegmentsWorker]] = Field(default=None, description="Technicians feasible for this slot, engine-ranked best first, each with its score breakdown.")
    best_time: Optional[StrictBool] = Field(default=None, description="True on the first slot of each day — the suggested \"BEST\" pick (UI hint).")
    business_time: Optional[JobRequestTimeSegmentsBusinessTime] = Field(default=None, description="The same arrival window expressed in BUSINESS-local time; its naive datetime is the value to send back on confirm.")
    datetime: Optional[datetime] = Field(default=None, description="Window start as an RFC3339 customer-local instant (with UTC offset).")
    ends_at: Optional[datetime] = Field(default=None, description="Span end (UTC) of a multi-day visit — render in business/customer timezone. Omitted for single-day slots.")
    multi_day: Optional[StrictBool] = Field(default=None, description="MultiDay flags a slot whose visit cannot finish in one day and spans consecutive days. EndsAt + Sessions are then populated (for the best-ranked candidate — the one auto-assign would pick) so the picker can show the customer \"this start runs until <EndsAt>, over N days\" BEFORE they confirm. Single-day slots leave these empty (the slot itself is the visit).")
    sessions: Optional[List[JobRequestSession]] = Field(default=None, description="Per-day session plan of a multi-day visit (for the best-ranked candidate). Omitted for single-day slots.")
    time: Optional[StrictStr] = Field(default=None, description="Arrival-window start, HH:MM customer-local.")
    time_end: Optional[StrictStr] = Field(default=None, description="Arrival-window end, HH:MM customer-local (= time + time_slot_step_minutes).")
    time_period: Optional[StrictInt] = Field(default=None, description="Period bucket of the window start: 1=morning, 2=afternoon, 3=evening.")
    time_period_label: Optional[StrictStr] = Field(default=None, description="Localized label for time_period.")
    workers_count: Optional[StrictInt] = Field(default=None, description="Number of entries in available_workers.")
    __properties: ClassVar[List[str]] = ["available_workers", "best_time", "business_time", "datetime", "ends_at", "multi_day", "sessions", "time", "time_end", "time_period", "time_period_label", "workers_count"]

    @field_validator('time_period')
    def time_period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3]):
            raise ValueError("must be one of enum values (1, 2, 3)")
        return value

    @field_validator('time_period_label')
    def time_period_label_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Morning', 'Afternoon', 'Evening']):
            raise ValueError("must be one of enum values ('Morning', 'Afternoon', 'Evening')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestTimeSegmentsSlot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_workers (list)
        _items = []
        if self.available_workers:
            for _item_available_workers in self.available_workers:
                if _item_available_workers:
                    _items.append(_item_available_workers.to_dict())
            _dict['available_workers'] = _items
        # override the default output from pydantic by calling `to_dict()` of business_time
        if self.business_time:
            _dict['business_time'] = self.business_time.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in sessions (list)
        _items = []
        if self.sessions:
            for _item_sessions in self.sessions:
                if _item_sessions:
                    _items.append(_item_sessions.to_dict())
            _dict['sessions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestTimeSegmentsSlot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available_workers": [JobRequestTimeSegmentsWorker.from_dict(_item) for _item in obj["available_workers"]] if obj.get("available_workers") is not None else None,
            "best_time": obj.get("best_time"),
            "business_time": JobRequestTimeSegmentsBusinessTime.from_dict(obj["business_time"]) if obj.get("business_time") is not None else None,
            "datetime": obj.get("datetime"),
            "ends_at": obj.get("ends_at"),
            "multi_day": obj.get("multi_day"),
            "sessions": [JobRequestSession.from_dict(_item) for _item in obj["sessions"]] if obj.get("sessions") is not None else None,
            "time": obj.get("time"),
            "time_end": obj.get("time_end"),
            "time_period": obj.get("time_period"),
            "time_period_label": obj.get("time_period_label"),
            "workers_count": obj.get("workers_count")
        })
        return _obj


