# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsenceAssignment(BaseModel):
    """
    JobRequestAbsenceAssignment
    """ # noqa: E501
    alternative_kind: Optional[StrictStr] = Field(default=None, description="Accepting an alternative: its kind, copied from alternatives[].kind. Omit for a strict placement from resolved[]. An unknown kind is ABSENCE_RESOLVE_INVALID_INPUT reason=unknown_alternative_kind (checked in the usecase, not at the binder).")
    end_at: Optional[datetime] = None
    job_id: StrictStr = Field(description="The job to re-staff (from preview.resolved[].job_id or preview.unresolved[].job_id).")
    start_at: Optional[datetime] = Field(default=None, description="REQUIRED for a reschedule kind: the new window, copied from alternatives[].start_at / end_at (RFC3339 UTC). Must be absent (or equal to the current window) for a strict or reassign_out_of_area placement.")
    status_version: StrictInt = Field(description="The job's status_version at preview time — the drift fence.")
    to_technician_id: StrictStr = Field(description="The technician receiving the job (from preview.resolved[].to_technician_id or alternatives[].to_technician_id).")
    __properties: ClassVar[List[str]] = ["alternative_kind", "end_at", "job_id", "start_at", "status_version", "to_technician_id"]

    @field_validator('alternative_kind')
    def alternative_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reassign_out_of_area', 'reschedule_same_day', 'reschedule_later_day']):
            raise ValueError("must be one of enum values ('reassign_out_of_area', 'reschedule_same_day', 'reschedule_later_day')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceAssignment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceAssignment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternative_kind": obj.get("alternative_kind"),
            "end_at": obj.get("end_at"),
            "job_id": obj.get("job_id"),
            "start_at": obj.get("start_at"),
            "status_version": obj.get("status_version"),
            "to_technician_id": obj.get("to_technician_id")
        })
        return _obj


