# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsenceSolver(BaseModel):
    """
    JobRequestAbsenceSolver
    """ # noqa: E501
    alternatives_truncated: Optional[StrictBool] = Field(default=None, description="The relaxation ladder ran out of its time budget: some unresolved rows carry fewer alternatives than exist. The strict plan (resolved[]) is complete regardless. Absent = false.")
    deterministic: Optional[StrictBool] = Field(default=None, description="Same input ⇒ same plan. Constant true in v1; soften copy at runtime if it ever reads false.")
    duration_ms: Optional[StrictInt] = Field(default=None, description="SERVER-side planner time in milliseconds (load → classify → rank → assign), never the request round-trip.")
    strategy: Optional[StrictStr] = Field(default=None, description="What actually ran: greedy_most_constrained_first (preview) | verify_previewed_plan (commit).")
    version: Optional[StrictStr] = Field(default=None, description="Planner version; bumped when ordering or padding rules change.")
    __properties: ClassVar[List[str]] = ["alternatives_truncated", "deterministic", "duration_ms", "strategy", "version"]

    @field_validator('strategy')
    def strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['greedy_most_constrained_first', 'verify_previewed_plan']):
            raise ValueError("must be one of enum values ('greedy_most_constrained_first', 'verify_previewed_plan')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceSolver from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceSolver from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternatives_truncated": obj.get("alternatives_truncated"),
            "deterministic": obj.get("deterministic"),
            "duration_ms": obj.get("duration_ms"),
            "strategy": obj.get("strategy"),
            "version": obj.get("version")
        })
        return _obj


