# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class JobRequestEmergencyCommitRequest(BaseModel):
    """
    JobRequestEmergencyCommitRequest
    """ # noqa: E501
    displacement_mode: Optional[StrictStr] = Field(default=None, description="Fate of displaced jobs: reschedule (default) or reassign — must match the preview.")
    emergency_expected_version: Optional[StrictInt] = Field(default=None, description="Optimistic-lock fence from the previewed job (0 = fence on the server-read version).")
    emergency_job_id: StrictStr = Field(description="ID of the P0 job to insert.")
    expected_move_ids: Optional[List[StrictStr]] = Field(default=None, description="ExpectedMoveIDs — the displaced job IDs the preview returned (echo BOTH data.days[].moves[].job_id AND data.reassignments[].job_id). RECOMMENDED: if the recomputed cascade would touch a different set (a job booked onto the lane since the preview), the commit is rejected with EMERGENCY_RESCHEDULE_PLAN_DRIFTED instead of displacing a job the coordinator never saw. Omit to opt out.")
    mode: StrictStr = Field(description="Cascade mode: overtime | next_day (must match the preview).")
    start_at: StrictStr = Field(description="Desired start — business-local naive datetime, no offset. Must be in the future and match the preview.")
    technician_id: StrictStr = Field(description="Target technician (must belong to the business).")
    __properties: ClassVar[List[str]] = ["displacement_mode", "emergency_expected_version", "emergency_job_id", "expected_move_ids", "mode", "start_at", "technician_id"]

    @field_validator('displacement_mode')
    def displacement_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reschedule', 'reassign']):
            raise ValueError("must be one of enum values ('reschedule', 'reassign')")
        return value

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['overtime', 'next_day']):
            raise ValueError("must be one of enum values ('overtime', 'next_day')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyCommitRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyCommitRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "displacement_mode": obj.get("displacement_mode"),
            "emergency_expected_version": obj.get("emergency_expected_version"),
            "emergency_job_id": obj.get("emergency_job_id"),
            "expected_move_ids": obj.get("expected_move_ids"),
            "mode": obj.get("mode"),
            "start_at": obj.get("start_at"),
            "technician_id": obj.get("technician_id")
        })
        return _obj


