# coding: utf-8

"""
    CrispHive Developer API

    Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_timeline_action import JobRequestTimelineAction
from typing import Optional, Set
from typing_extensions import Self

class JobRequestTimelineEvent(BaseModel):
    """
    JobRequestTimelineEvent
    """ # noqa: E501
    actions: Optional[List[JobRequestTimelineAction]] = Field(default=None, description="Actions declared for this status, in workflow order. Omitted when none.")
    display_name: Optional[StrictStr] = Field(default=None, description="Status display name, resolved to the request locale.")
    entered_at: Optional[datetime] = Field(default=None, description="When the job entered this status (UTC); null for upcoming steps or jobs missing the backfill.")
    state: Optional[StrictStr] = Field(default=None, description="Where this status sits relative to the job's progress.")
    status_key: Optional[StrictStr] = Field(default=None, description="Workflow status key for this row.")
    __properties: ClassVar[List[str]] = ["actions", "display_name", "entered_at", "state", "status_key"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['completed', 'current', 'upcoming']):
            raise ValueError("must be one of enum values ('completed', 'current', 'upcoming')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestTimelineEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestTimelineEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actions": [JobRequestTimelineAction.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "display_name": obj.get("display_name"),
            "entered_at": obj.get("entered_at"),
            "state": obj.get("state"),
            "status_key": obj.get("status_key")
        })
        return _obj


