# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_move_warning import JobRequestMoveWarning
from crisphive.models.job_request_reschedule_day import JobRequestRescheduleDay
from crisphive.models.job_request_reschedule_reassignment import JobRequestRescheduleReassignment
from typing import Optional, Set
from typing_extensions import Self

class JobRequestEmergencyPlan(BaseModel):
    """
    JobRequestEmergencyPlan
    """ # noqa: E501
    business_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone the per-day groupings are rendered in.")
    days: Optional[List[JobRequestRescheduleDay]] = Field(default=None, description="Pushed jobs grouped per business-local calendar day.")
    emergency_end: Optional[datetime] = Field(default=None, description="Emergency visit window end (UTC) — start + the quoted visit duration (job + mobilization + demobilization).")
    emergency_job_id: Optional[StrictStr] = Field(default=None, description="ID of the inserted P0 job.")
    emergency_start: Optional[datetime] = Field(default=None, description="Emergency visit window start (UTC).")
    mode: Optional[StrictStr] = Field(default=None, description="Cascade mode the plan assumed (overtime | next_day).")
    reassignments: Optional[List[JobRequestRescheduleReassignment]] = Field(default=None, description="Displaced jobs handed to an ALTERNATE technician at their original window (displacement_mode=reassign; empty otherwise). Jobs that could not be re-staffed remain in days/total_moves (reschedule fallback).")
    technician_id: Optional[StrictStr] = Field(default=None, description="Technician the emergency lands on.")
    total_moves: Optional[StrictInt] = Field(default=None, description="Number of displaced jobs pushed to a later window.")
    warnings: Optional[List[JobRequestMoveWarning]] = Field(default=None, description="Non-blocking consequences the coordinator accepts by committing (TIME_OFF_OVERLAP per displaced job landing in the tech's approved leave).")
    __properties: ClassVar[List[str]] = ["business_timezone", "days", "emergency_end", "emergency_job_id", "emergency_start", "mode", "reassignments", "technician_id", "total_moves", "warnings"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['overtime', 'next_day']):
            raise ValueError("must be one of enum values ('overtime', 'next_day')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyPlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in days (list)
        _items = []
        if self.days:
            for _item_days in self.days:
                if _item_days:
                    _items.append(_item_days.to_dict())
            _dict['days'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in reassignments (list)
        _items = []
        if self.reassignments:
            for _item_reassignments in self.reassignments:
                if _item_reassignments:
                    _items.append(_item_reassignments.to_dict())
            _dict['reassignments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyPlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_timezone": obj.get("business_timezone"),
            "days": [JobRequestRescheduleDay.from_dict(_item) for _item in obj["days"]] if obj.get("days") is not None else None,
            "emergency_end": obj.get("emergency_end"),
            "emergency_job_id": obj.get("emergency_job_id"),
            "emergency_start": obj.get("emergency_start"),
            "mode": obj.get("mode"),
            "reassignments": [JobRequestRescheduleReassignment.from_dict(_item) for _item in obj["reassignments"]] if obj.get("reassignments") is not None else None,
            "technician_id": obj.get("technician_id"),
            "total_moves": obj.get("total_moves"),
            "warnings": [JobRequestMoveWarning.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        })
        return _obj


