# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_absence_resolved_job import JobRequestAbsenceResolvedJob
from crisphive.models.job_request_absence_solver import JobRequestAbsenceSolver
from crisphive.models.job_request_absence_time_off import JobRequestAbsenceTimeOff
from crisphive.models.job_request_absence_unresolved_job import JobRequestAbsenceUnresolvedJob
from crisphive.models.job_request_move_warning import JobRequestMoveWarning
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsencePlan(BaseModel):
    """
    JobRequestAbsencePlan
    """ # noqa: E501
    business_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone the calendar days are read in.")
    var_date: Optional[date] = Field(default=None, description="First / last day of the absence (YYYY-MM-DD, business-local, inclusive).", alias="date")
    orphaned_count: Optional[StrictInt] = Field(default=None, description="Jobs on the technician's board inside the range that the plan considered.")
    resolved: Optional[List[JobRequestAbsenceResolvedJob]] = Field(default=None, description="Jobs handed to an alternate at their unchanged window (empty array, never null).")
    solver: Optional[JobRequestAbsenceSolver] = Field(default=None, description="Planner metadata.")
    technician_id: Optional[StrictStr] = Field(default=None, description="The absent technician.")
    technician_name: Optional[StrictStr] = Field(default=None, description="Full name of the absent technician.")
    time_offs: Optional[List[JobRequestAbsenceTimeOff]] = Field(default=None, description="Commit only: every time-off record the commit relied on for coverage — a pending one CONTAINED in the range is approved by the commit; an approved one is reported as-is.")
    unresolved: Optional[List[JobRequestAbsenceUnresolvedJob]] = Field(default=None, description="Jobs left for the coordinator, each with a reason (empty array, never null).")
    until_date: Optional[date] = None
    warnings: Optional[List[JobRequestMoveWarning]] = Field(default=None, description="Non-blocking consequences (same vocabulary as the move/emergency plans). Empty in v1.")
    __properties: ClassVar[List[str]] = ["business_timezone", "date", "orphaned_count", "resolved", "solver", "technician_id", "technician_name", "time_offs", "unresolved", "until_date", "warnings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsencePlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in resolved (list)
        _items = []
        if self.resolved:
            for _item_resolved in self.resolved:
                if _item_resolved:
                    _items.append(_item_resolved.to_dict())
            _dict['resolved'] = _items
        # override the default output from pydantic by calling `to_dict()` of solver
        if self.solver:
            _dict['solver'] = self.solver.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in time_offs (list)
        _items = []
        if self.time_offs:
            for _item_time_offs in self.time_offs:
                if _item_time_offs:
                    _items.append(_item_time_offs.to_dict())
            _dict['time_offs'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in unresolved (list)
        _items = []
        if self.unresolved:
            for _item_unresolved in self.unresolved:
                if _item_unresolved:
                    _items.append(_item_unresolved.to_dict())
            _dict['unresolved'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsencePlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_timezone": obj.get("business_timezone"),
            "date": obj.get("date"),
            "orphaned_count": obj.get("orphaned_count"),
            "resolved": [JobRequestAbsenceResolvedJob.from_dict(_item) for _item in obj["resolved"]] if obj.get("resolved") is not None else None,
            "solver": JobRequestAbsenceSolver.from_dict(obj["solver"]) if obj.get("solver") is not None else None,
            "technician_id": obj.get("technician_id"),
            "technician_name": obj.get("technician_name"),
            "time_offs": [JobRequestAbsenceTimeOff.from_dict(_item) for _item in obj["time_offs"]] if obj.get("time_offs") is not None else None,
            "unresolved": [JobRequestAbsenceUnresolvedJob.from_dict(_item) for _item in obj["unresolved"]] if obj.get("unresolved") is not None else None,
            "until_date": obj.get("until_date"),
            "warnings": [JobRequestMoveWarning.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        })
        return _obj


