# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from crisphive.models.job_request_crew_member_input import JobRequestCrewMemberInput
from typing import Optional, Set
from typing_extensions import Self

class JobRequestQuoteRequest(BaseModel):
    """
    JobRequestQuoteRequest
    """ # noqa: E501
    crew: Optional[Annotated[List[JobRequestCrewMemberInput], Field(max_length=20)]] = Field(default=None, description="Crew — multi-person plan (tech lead + buddies). Omit / empty = single person (lead 100%). When present must have exactly one is_lead and wrench_percent summing to 100. See MULTIPERSON_CREW_DESIGN.md.")
    demobilization_minutes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Demobilization (teardown) minutes added after the work. Optional, min 0.")
    job_duration_minutes: Annotated[int, Field(strict=True, ge=1)] = Field(description="Hands-on work duration in minutes (man-minutes for a crew job). Required, min 1.")
    mobilization_minutes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Mobilization (setup/travel-prep) minutes added before the work. Optional, min 0.")
    status_version: Optional[StrictInt] = Field(default=None, description="Optimistic-lock fence: the status_version from your last read. Omitted/0 = fence on the row's current version (no race protection).")
    __properties: ClassVar[List[str]] = ["crew", "demobilization_minutes", "job_duration_minutes", "mobilization_minutes", "status_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestQuoteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in crew (list)
        _items = []
        if self.crew:
            for _item_crew in self.crew:
                if _item_crew:
                    _items.append(_item_crew.to_dict())
            _dict['crew'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestQuoteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "crew": [JobRequestCrewMemberInput.from_dict(_item) for _item in obj["crew"]] if obj.get("crew") is not None else None,
            "demobilization_minutes": obj.get("demobilization_minutes"),
            "job_duration_minutes": obj.get("job_duration_minutes"),
            "mobilization_minutes": obj.get("mobilization_minutes"),
            "status_version": obj.get("status_version")
        })
        return _obj


