# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from crisphive.models.job_request_absence_alternative_cost import JobRequestAbsenceAlternativeCost
from crisphive.models.job_request_absence_notification import JobRequestAbsenceNotification
from typing import Optional, Set
from typing_extensions import Self

class JobRequestAbsenceResolvedJob(BaseModel):
    """
    JobRequestAbsenceResolvedJob
    """ # noqa: E501
    alternative_kind: Optional[StrictStr] = Field(default=None, description="Commit only, when the placement came from unresolved[].alternatives[]: the accepted kind. Absent for a strict placement. EXTEND-ONLY.")
    attention_cleared: Optional[StrictBool] = Field(default=None, description="Commit only: the job's \"needs attention\" flag was cleared in the same write.")
    booked_minutes: Optional[StrictInt] = Field(default=None, description="Minutes the alternate already has booked that day (load).")
    cost: Optional[JobRequestAbsenceAlternativeCost] = Field(default=None, description="Commit only, with alternative_kind: what the business paid for this placement.")
    customer_name: Optional[StrictStr] = Field(default=None, description="Customer name on the job.")
    var_date: Optional[date] = Field(default=None, description="Business-local calendar day the window starts on (YYYY-MM-DD) — group a multi-day range on it.", alias="date")
    desired_skills: Optional[StrictInt] = None
    distance_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Alternate's driving distance to the site in km. ABSENT when the engine had no route (no start location, no job coordinates, routing failure) — hide the chip rather than rendering \"0 km\".")
    end_at: Optional[datetime] = Field(default=None, description="Window end (UTC).")
    feasible_count: Optional[StrictInt] = Field(default=None, description="How many alternates could have taken this job.")
    from_technician_id: Optional[StrictStr] = Field(default=None, description="UUID of the absent technician losing the job.")
    job_id: Optional[StrictStr] = Field(default=None, description="UUID of the re-staffed job.")
    matched_skills: Optional[StrictInt] = Field(default=None, description="Desired skills the alternate holds / the job asks for.")
    notification: Optional[JobRequestAbsenceNotification] = Field(default=None, description="Commit only: what the customer-notification routing will do for this job.")
    original_end_at: Optional[datetime] = None
    original_start_at: Optional[datetime] = Field(default=None, description="Commit only, when window_preserved is false: the window the job LEFT (UTC).")
    priority: Optional[StrictStr] = Field(default=None, description="Priority (p0..p3).")
    short_code: Optional[StrictStr] = Field(default=None, description="Human-friendly short code.")
    start_at: Optional[datetime] = Field(default=None, description="Window start (UTC). For a strict or reassign_out_of_area placement it is byte-identical to the job's current window; for an accepted reschedule alternative (commit) it is the NEW window.")
    status_version: Optional[StrictInt] = Field(default=None, description="status_version: at preview the current value (echo it on commit); on the COMMIT response the post-commit value (+1).")
    to_name: Optional[StrictStr] = Field(default=None, description="Full name of the alternate. Omitted when unresolved.")
    to_technician_id: Optional[StrictStr] = Field(default=None, description="UUID of the alternate receiving the job.")
    total_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Engine ranking score for this alternate on this job (0..1).")
    travel_minutes: Optional[StrictInt] = Field(default=None, description="Alternate's one-way commute estimate in minutes (rounded up). Absent when unknown.")
    window_preserved: Optional[StrictBool] = Field(default=None, description="True unless the coordinator accepted a reschedule alternative — then false, and original_start_at/original_end_at carry the window the job left.")
    __properties: ClassVar[List[str]] = ["alternative_kind", "attention_cleared", "booked_minutes", "cost", "customer_name", "date", "desired_skills", "distance_km", "end_at", "feasible_count", "from_technician_id", "job_id", "matched_skills", "notification", "original_end_at", "original_start_at", "priority", "short_code", "start_at", "status_version", "to_name", "to_technician_id", "total_score", "travel_minutes", "window_preserved"]

    @field_validator('alternative_kind')
    def alternative_kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['reassign_out_of_area', 'reschedule_same_day', 'reschedule_later_day']):
            raise ValueError("must be one of enum values ('reassign_out_of_area', 'reschedule_same_day', 'reschedule_later_day')")
        return value

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['p0', 'p1', 'p2', 'p3']):
            raise ValueError("must be one of enum values ('p0', 'p1', 'p2', 'p3')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceResolvedJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of cost
        if self.cost:
            _dict['cost'] = self.cost.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notification
        if self.notification:
            _dict['notification'] = self.notification.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestAbsenceResolvedJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alternative_kind": obj.get("alternative_kind"),
            "attention_cleared": obj.get("attention_cleared"),
            "booked_minutes": obj.get("booked_minutes"),
            "cost": JobRequestAbsenceAlternativeCost.from_dict(obj["cost"]) if obj.get("cost") is not None else None,
            "customer_name": obj.get("customer_name"),
            "date": obj.get("date"),
            "desired_skills": obj.get("desired_skills"),
            "distance_km": obj.get("distance_km"),
            "end_at": obj.get("end_at"),
            "feasible_count": obj.get("feasible_count"),
            "from_technician_id": obj.get("from_technician_id"),
            "job_id": obj.get("job_id"),
            "matched_skills": obj.get("matched_skills"),
            "notification": JobRequestAbsenceNotification.from_dict(obj["notification"]) if obj.get("notification") is not None else None,
            "original_end_at": obj.get("original_end_at"),
            "original_start_at": obj.get("original_start_at"),
            "priority": obj.get("priority"),
            "short_code": obj.get("short_code"),
            "start_at": obj.get("start_at"),
            "status_version": obj.get("status_version"),
            "to_name": obj.get("to_name"),
            "to_technician_id": obj.get("to_technician_id"),
            "total_score": obj.get("total_score"),
            "travel_minutes": obj.get("travel_minutes"),
            "window_preserved": obj.get("window_preserved")
        })
        return _obj


