# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from crisphive.models.internal_jobrequest_http_address_req import InternalJobrequestHttpAddressReq
from crisphive.models.job_request_book_and_confirm_customer import JobRequestBookAndConfirmCustomer
from typing import Optional, Set
from typing_extensions import Self

class JobRequestBookAndConfirmRequest(BaseModel):
    """
    JobRequestBookAndConfirmRequest
    """ # noqa: E501
    address: Optional[InternalJobrequestHttpAddressReq] = Field(default=None, description="Service address. REQUIRED with `customer`; ignored with `customer_id` (the stored customer address is used). Missing coordinates are geocoded.")
    customer: Optional[JobRequestBookAndConfirmCustomer] = Field(default=None, description="A caller who may or may not exist yet: matched by phone/email against the business's customers (no duplicate is created for a known caller), created otherwise. Send this OR `customer_id`.")
    customer_id: Optional[StrictStr] = Field(default=None, description="UUID of an existing customer. Send this OR `customer`, not both.")
    description: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="Free-text description of the work. Optional; max 2000 chars.")
    job_duration_minutes: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="Hands-on work minutes. Optional when the job type has a default_duration_minutes.")
    job_type_id: Optional[StrictStr] = Field(default=None, description="UUID of the job type: it classifies the job and supplies default_duration_minutes when job_duration_minutes is omitted. Optional: omitted, the business's DEFAULT job type (is_default, the seeded \"General\", 60 min + 15 + 15 unless the business changed it) is used.")
    priority: Optional[StrictStr] = Field(default=None, description="Scheduling priority p0–p3. Optional; omitted = the business default.")
    scheduled_at: Optional[datetime] = Field(default=None, description="Start time — a BUSINESS-LOCAL wall clock, same rule as confirmJobRequest: canonical `2026-09-30T10:00:00`, seconds optional, a space may replace the T; an offset is accepted only when it agrees with the business timezone. Must be in the future.")
    skill_ids: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = Field(default=None, description="UUIDs of skills the work needs. Optional; up to 20.")
    technician_id: Optional[StrictStr] = Field(default=None, description="Force a specific lead technician (feasibility still enforced). Omit to let Crisphive pick.")
    __properties: ClassVar[List[str]] = ["address", "customer", "customer_id", "description", "job_duration_minutes", "job_type_id", "priority", "scheduled_at", "skill_ids", "technician_id"]

    @field_validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['p0', 'p1', 'p2', 'p3']):
            raise ValueError("must be one of enum values ('p0', 'p1', 'p2', 'p3')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestBookAndConfirmRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of address
        if self.address:
            _dict['address'] = self.address.to_dict()
        # override the default output from pydantic by calling `to_dict()` of customer
        if self.customer:
            _dict['customer'] = self.customer.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestBookAndConfirmRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": InternalJobrequestHttpAddressReq.from_dict(obj["address"]) if obj.get("address") is not None else None,
            "customer": JobRequestBookAndConfirmCustomer.from_dict(obj["customer"]) if obj.get("customer") is not None else None,
            "customer_id": obj.get("customer_id"),
            "description": obj.get("description"),
            "job_duration_minutes": obj.get("job_duration_minutes"),
            "job_type_id": obj.get("job_type_id"),
            "priority": obj.get("priority"),
            "scheduled_at": obj.get("scheduled_at"),
            "skill_ids": obj.get("skill_ids"),
            "technician_id": obj.get("technician_id")
        })
        return _obj


