# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from crisphive.models.job_request_reschedule_day import JobRequestRescheduleDay
from typing import Optional, Set
from typing_extensions import Self

class JobRequestEmergencyCandidate(BaseModel):
    """
    JobRequestEmergencyCandidate
    """ # noqa: E501
    booked_minutes: Optional[StrictInt] = Field(default=None, description="Minutes of work already booked on this technician that day (workload context).")
    days: Optional[List[JobRequestRescheduleDay]] = Field(default=None, description="The displaced jobs, grouped per business-local day (same shape as the preview endpoint) — what the coordinator reviews before committing.")
    distance_km: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Estimated distance from the tech's start location to the site, in kilometers.")
    full_name: Optional[StrictStr] = Field(default=None, description="Candidate technician's full name.")
    matched_skills: Optional[StrictInt] = Field(default=None, description="Number of the job's desired skills this technician matches.")
    technician_id: Optional[StrictStr] = Field(default=None, description="UUID of the candidate technician.")
    total_moves: Optional[StrictInt] = Field(default=None, description="How many jobs choosing this tech would push (0 = free slot).")
    total_score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Smart-assign engine ranking score (higher = better fit).")
    travel_minutes: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ETA estimate in minutes from the tech's start location to the site — static origin (no live GPS), rank hint not a promise.")
    __properties: ClassVar[List[str]] = ["booked_minutes", "days", "distance_km", "full_name", "matched_skills", "technician_id", "total_moves", "total_score", "travel_minutes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyCandidate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in days (list)
        _items = []
        if self.days:
            for _item_days in self.days:
                if _item_days:
                    _items.append(_item_days.to_dict())
            _dict['days'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestEmergencyCandidate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "booked_minutes": obj.get("booked_minutes"),
            "days": [JobRequestRescheduleDay.from_dict(_item) for _item in obj["days"]] if obj.get("days") is not None else None,
            "distance_km": obj.get("distance_km"),
            "full_name": obj.get("full_name"),
            "matched_skills": obj.get("matched_skills"),
            "technician_id": obj.get("technician_id"),
            "total_moves": obj.get("total_moves"),
            "total_score": obj.get("total_score"),
            "travel_minutes": obj.get("travel_minutes")
        })
        return _obj


