# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_date import JobDate
from crisphive.models.job_request_arrival_window import JobRequestArrivalWindow
from crisphive.models.job_request_session import JobRequestSession
from typing import Optional, Set
from typing_extensions import Self

class JobRequestSchedule(BaseModel):
    """
    JobRequestSchedule
    """ # noqa: E501
    arrival_window: Optional[JobRequestArrivalWindow] = Field(default=None, description="ArrivalWindow is the [start, start+window_minutes] arrival window the customer sees after confirming. start/end UTC — render in business/customer timezone. Omitted until confirmed.")
    business_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone of the business. Omitted if unknown.")
    customer_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone of the customer. Omitted if unknown.")
    ends_at: Optional[datetime] = Field(default=None, description="EndsAt is the job's span END (last session end, UTC). For a multi-day job it falls on a LATER calendar day than scheduled_at — render \"starts D1 → ends Dn\". Nil when no session plan exists.")
    job_dates: Optional[List[JobDate]] = Field(default=None, description="Requested date(s)/period(s) captured at booking. Omitted once confirmed/scheduled. Use regional.JobDate directly (not the jobrequest.JobDate alias) so swag emits a single canonical `JobDate` schema instead of an aliased duplicate.")
    scheduled_at: Optional[datetime] = Field(default=None, description="Confirmed start time (UTC); null until the customer confirms. Render in business/customer timezone.")
    scheduled_duration_minutes: Optional[StrictInt] = Field(default=None, description="Total scheduled duration in minutes (job + mobilization + demobilization); null until quoted.")
    sessions: Optional[List[JobRequestSession]] = Field(default=None, description="Sessions is the per-day on-site breakdown (ordered): one for single-day, several for multi-day.")
    __properties: ClassVar[List[str]] = ["arrival_window", "business_timezone", "customer_timezone", "ends_at", "job_dates", "scheduled_at", "scheduled_duration_minutes", "sessions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of arrival_window
        if self.arrival_window:
            _dict['arrival_window'] = self.arrival_window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in job_dates (list)
        _items = []
        if self.job_dates:
            for _item_job_dates in self.job_dates:
                if _item_job_dates:
                    _items.append(_item_job_dates.to_dict())
            _dict['job_dates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sessions (list)
        _items = []
        if self.sessions:
            for _item_sessions in self.sessions:
                if _item_sessions:
                    _items.append(_item_sessions.to_dict())
            _dict['sessions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arrival_window": JobRequestArrivalWindow.from_dict(obj["arrival_window"]) if obj.get("arrival_window") is not None else None,
            "business_timezone": obj.get("business_timezone"),
            "customer_timezone": obj.get("customer_timezone"),
            "ends_at": obj.get("ends_at"),
            "job_dates": [JobDate.from_dict(_item) for _item in obj["job_dates"]] if obj.get("job_dates") is not None else None,
            "scheduled_at": obj.get("scheduled_at"),
            "scheduled_duration_minutes": obj.get("scheduled_duration_minutes"),
            "sessions": [JobRequestSession.from_dict(_item) for _item in obj["sessions"]] if obj.get("sessions") is not None else None
        })
        return _obj


