# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.job_request_crew_change import JobRequestCrewChange
from crisphive.models.job_request_move_member import JobRequestMoveMember
from crisphive.models.job_request_move_warning import JobRequestMoveWarning
from crisphive.models.job_request_reschedule_day import JobRequestRescheduleDay
from typing import Optional, Set
from typing_extensions import Self

class JobRequestMovePlan(BaseModel):
    """
    JobRequestMovePlan
    """ # noqa: E501
    business_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone the per-day groupings are rendered in.")
    crew_changes: Optional[List[JobRequestCrewChange]] = Field(default=None, description="Crew-job move: proposed member swaps (current member busy at the new time → auto-replaced by the best same-tier candidate). Committing the plan approves them. Omitted for single-person jobs / no swaps.")
    days: Optional[List[JobRequestRescheduleDay]] = Field(default=None, description="Displaced jobs grouped per business-local calendar day.")
    job_id: Optional[StrictStr] = Field(default=None, description="UUID of the moved job.")
    members: Optional[List[JobRequestMoveMember]] = Field(default=None, description="Crew-job move: the FULL member plan at the new time (kept AND swapped members, each with their window + travel) — review F2: previously computed but never surfaced. Omitted for single-person jobs.")
    mode: Optional[StrictStr] = Field(default=None, description="Cascade mode the plan assumed (overtime | next_day).")
    new_end: Optional[datetime] = Field(default=None, description="The moved job's new window end (UTC).")
    new_start: Optional[datetime] = Field(default=None, description="The moved job's new window start (UTC).")
    previous_technician_id: Optional[StrictStr] = Field(default=None, description="UUID of the technician the job moved OFF (manual reassign only). Omitted on a pure time move.")
    short_code: Optional[StrictStr] = Field(default=None, description="Human-friendly short code of the moved job.")
    technician_id: Optional[StrictStr] = Field(default=None, description="UUID of the technician the job lands on.")
    total_moves: Optional[StrictInt] = Field(default=None, description="Number of displaced jobs pushed to a later window.")
    warnings: Optional[List[JobRequestMoveWarning]] = Field(default=None, description="Non-blocking consequences the coordinator accepts by committing.")
    __properties: ClassVar[List[str]] = ["business_timezone", "crew_changes", "days", "job_id", "members", "mode", "new_end", "new_start", "previous_technician_id", "short_code", "technician_id", "total_moves", "warnings"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['overtime', 'next_day']):
            raise ValueError("must be one of enum values ('overtime', 'next_day')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobRequestMovePlan from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in crew_changes (list)
        _items = []
        if self.crew_changes:
            for _item_crew_changes in self.crew_changes:
                if _item_crew_changes:
                    _items.append(_item_crew_changes.to_dict())
            _dict['crew_changes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in days (list)
        _items = []
        if self.days:
            for _item_days in self.days:
                if _item_days:
                    _items.append(_item_days.to_dict())
            _dict['days'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in members (list)
        _items = []
        if self.members:
            for _item_members in self.members:
                if _item_members:
                    _items.append(_item_members.to_dict())
            _dict['members'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in warnings (list)
        _items = []
        if self.warnings:
            for _item_warnings in self.warnings:
                if _item_warnings:
                    _items.append(_item_warnings.to_dict())
            _dict['warnings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobRequestMovePlan from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_timezone": obj.get("business_timezone"),
            "crew_changes": [JobRequestCrewChange.from_dict(_item) for _item in obj["crew_changes"]] if obj.get("crew_changes") is not None else None,
            "days": [JobRequestRescheduleDay.from_dict(_item) for _item in obj["days"]] if obj.get("days") is not None else None,
            "job_id": obj.get("job_id"),
            "members": [JobRequestMoveMember.from_dict(_item) for _item in obj["members"]] if obj.get("members") is not None else None,
            "mode": obj.get("mode"),
            "new_end": obj.get("new_end"),
            "new_start": obj.get("new_start"),
            "previous_technician_id": obj.get("previous_technician_id"),
            "short_code": obj.get("short_code"),
            "technician_id": obj.get("technician_id"),
            "total_moves": obj.get("total_moves"),
            "warnings": [JobRequestMoveWarning.from_dict(_item) for _item in obj["warnings"]] if obj.get("warnings") is not None else None
        })
        return _obj


