# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.technician_schedule_block import TechnicianScheduleBlock
from crisphive.models.technician_schedule_session import TechnicianScheduleSession
from typing import Optional, Set
from typing_extensions import Self

class TechnicianSchedule(BaseModel):
    """
    TechnicianSchedule
    """ # noqa: E501
    business_timezone: Optional[StrictStr] = Field(default=None, description="IANA timezone the from/to dates were interpreted in.")
    var_from: Optional[datetime] = Field(default=None, description="Resolved query window start (UTC).", alias="from")
    sessions: Optional[List[TechnicianScheduleSession]] = Field(default=None, description="Job blocks occupying the technician's lane, time-ordered.")
    technician_id: Optional[StrictStr] = Field(default=None, description="The technician queried.")
    technician_name: Optional[StrictStr] = Field(default=None, description="The technician's full name.")
    time_off: Optional[List[TechnicianScheduleBlock]] = Field(default=None, description="Approved time-off blocks inside the window.")
    to: Optional[datetime] = Field(default=None, description="Resolved query window end (UTC).")
    __properties: ClassVar[List[str]] = ["business_timezone", "from", "sessions", "technician_id", "technician_name", "time_off", "to"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TechnicianSchedule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sessions (list)
        _items = []
        if self.sessions:
            for _item_sessions in self.sessions:
                if _item_sessions:
                    _items.append(_item_sessions.to_dict())
            _dict['sessions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in time_off (list)
        _items = []
        if self.time_off:
            for _item_time_off in self.time_off:
                if _item_time_off:
                    _items.append(_item_time_off.to_dict())
            _dict['time_off'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TechnicianSchedule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "business_timezone": obj.get("business_timezone"),
            "from": obj.get("from"),
            "sessions": [TechnicianScheduleSession.from_dict(_item) for _item in obj["sessions"]] if obj.get("sessions") is not None else None,
            "technician_id": obj.get("technician_id"),
            "technician_name": obj.get("technician_name"),
            "time_off": [TechnicianScheduleBlock.from_dict(_item) for _item in obj["time_off"]] if obj.get("time_off") is not None else None,
            "to": obj.get("to")
        })
        return _obj


