# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.api_internal_techtimeoff_actions import ApiInternalTechtimeoffActions
from crisphive.models.api_internal_techtimeoff_status import ApiInternalTechtimeoffStatus
from typing import Optional, Set
from typing_extensions import Self

class TechnicianTimeOff(BaseModel):
    """
    TechnicianTimeOff
    """ # noqa: E501
    actions: Optional[ApiInternalTechtimeoffActions] = Field(default=None, description="Which dashboard actions the caller may take on this record.")
    business_id: Optional[StrictStr] = Field(default=None, description="Owning business.")
    created_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
    end_datetime: Optional[datetime] = Field(default=None, description="Block end (RFC3339 instant, UTC).")
    id: Optional[StrictStr] = Field(default=None, description="UUID of the record.")
    reason: Optional[StrictStr] = Field(default=None, description="Free-text reason.")
    start_datetime: Optional[datetime] = Field(default=None, description="Block start (RFC3339 instant, UTC).")
    status: Optional[ApiInternalTechtimeoffStatus] = Field(default=None, description="pending (awaiting approval — the engine does NOT honour it yet) | approved (blocks scheduling) | rejected | cancelled.")
    technician_id: Optional[StrictStr] = Field(default=None, description="The technician the block belongs to.")
    updated_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["actions", "business_id", "created_at", "deleted_at", "end_datetime", "id", "reason", "start_datetime", "status", "technician_id", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TechnicianTimeOff from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of actions
        if self.actions:
            _dict['actions'] = self.actions.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TechnicianTimeOff from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actions": ApiInternalTechtimeoffActions.from_dict(obj["actions"]) if obj.get("actions") is not None else None,
            "business_id": obj.get("business_id"),
            "created_at": obj.get("created_at"),
            "deleted_at": obj.get("deleted_at"),
            "end_datetime": obj.get("end_datetime"),
            "id": obj.get("id"),
            "reason": obj.get("reason"),
            "start_datetime": obj.get("start_datetime"),
            "status": obj.get("status"),
            "technician_id": obj.get("technician_id"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


