# coding: utf-8

"""
    Crisphive Developer API

    Public REST API for integrating Crisphive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class VehicleUpdateRequest(BaseModel):
    """
    VehicleUpdateRequest
    """ # noqa: E501
    brand: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="nil = keep; \"\" clears the field.")
    current_mileage: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    model: Optional[Annotated[str, Field(strict=True, max_length=50)]] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="nil = keep. min=1 rejects an explicit \"\" (a vehicle needs a name); omitempty is what lets a nil pointer skip validation entirely.")
    owner_id: Optional[StrictStr] = Field(default=None, description="nil = keep the current owner; \"\" clears it; a UUID sets it.")
    plate_number: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    status: Optional[StrictStr] = None
    vehicle_type: Optional[StrictStr] = Field(default=None, description="nil = keep; a non-nil value must be a known enum member.")
    year: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["brand", "current_mileage", "model", "name", "owner_id", "plate_number", "status", "vehicle_type", "year"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['inactive', 'idle', 'on_job', 'maintenance']):
            raise ValueError("must be one of enum values ('inactive', 'idle', 'on_job', 'maintenance')")
        return value

    @field_validator('vehicle_type')
    def vehicle_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['van', 'truck', 'car']):
            raise ValueError("must be one of enum values ('van', 'truck', 'car')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VehicleUpdateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VehicleUpdateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "brand": obj.get("brand"),
            "current_mileage": obj.get("current_mileage"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "plate_number": obj.get("plate_number"),
            "status": obj.get("status"),
            "vehicle_type": obj.get("vehicle_type"),
            "year": obj.get("year")
        })
        return _obj


