# coding: utf-8

"""
    CrispHive Developer API

    Public REST API for integrating CrispHive from your own backend. Authenticate every request with a secret API key as a Bearer token (`Authorization: Bearer chsk_live_…`). The key prefix selects the data environment: `chsk_live_…` → production (live), `chsk_test_…` → sandbox (isolated test).  **Key scopes (restricted keys).** A key is either *full-access* (can call every endpoint below) or *restricted* to a set of permission codes chosen at creation — the same codes as the dashboard permission grid (e.g. `customers_view`, `job_create`, `team_manage`). A restricted key calling an endpoint outside its scope gets `403`. The full code list is the permission catalog (`GET /permission/modules` on the dashboard API). Create, scope, and revoke keys from the business dashboard.  Every response is wrapped in the envelope `{ \"error_code\": 0, \"message\": \"Success\", \"data\": <payload> }`.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from crisphive.models.vehicle_owner import VehicleOwner
from typing import Optional, Set
from typing_extensions import Self

class Vehicle(BaseModel):
    """
    Vehicle
    """ # noqa: E501
    brand: Optional[StrictStr] = Field(default=None, description="Manufacturer / make (e.g. \"Ford\"). Empty if not set.")
    business_id: Optional[StrictStr] = Field(default=None, description="UUID of the business that owns this vehicle.")
    created_at: Optional[datetime] = Field(default=None, description="When the vehicle record was created (RFC3339).")
    current_mileage: Optional[StrictInt] = Field(default=None, description="Current odometer reading; null if not tracked.")
    deleted_at: Optional[datetime] = Field(default=None, description="Set (RFC3339) only when the record has been soft-deleted; omitted otherwise.")
    id: Optional[StrictStr] = Field(default=None, description="Vehicle UUID — the stable identifier used in every vehicle endpoint.")
    model: Optional[StrictStr] = Field(default=None, description="Model name (e.g. \"Transit\"). Empty if not set.")
    name: Optional[StrictStr] = Field(default=None, description="Vehicle display name.")
    owner: Optional[VehicleOwner] = Field(default=None, description="The technician who currently owns (claimed) this vehicle; null if unowned.")
    plate_number: Optional[StrictStr] = Field(default=None, description="License plate number. Empty if not set.")
    status: Optional[StrictStr] = Field(default=None, description="Operational status.")
    technician_ids: Optional[List[StrictStr]] = Field(default=None, description="UUIDs of technicians who use this vehicle (derived from each technician's vehicle list). Empty array if none.")
    updated_at: Optional[datetime] = Field(default=None, description="When the vehicle record was last modified (RFC3339).")
    utilization_percent: Optional[StrictInt] = Field(default=None, description="Percentage of capacity the vehicle is utilized (0–100).")
    vehicle_type: Optional[StrictStr] = Field(default=None, description="Vehicle category.")
    year: Optional[StrictInt] = Field(default=None, description="Model year. Zero if not set.")
    __properties: ClassVar[List[str]] = ["brand", "business_id", "created_at", "current_mileage", "deleted_at", "id", "model", "name", "owner", "plate_number", "status", "technician_ids", "updated_at", "utilization_percent", "vehicle_type", "year"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['inactive', 'idle', 'on_job', 'maintenance']):
            raise ValueError("must be one of enum values ('inactive', 'idle', 'on_job', 'maintenance')")
        return value

    @field_validator('vehicle_type')
    def vehicle_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['van', 'truck', 'car']):
            raise ValueError("must be one of enum values ('van', 'truck', 'car')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Vehicle from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Vehicle from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "brand": obj.get("brand"),
            "business_id": obj.get("business_id"),
            "created_at": obj.get("created_at"),
            "current_mileage": obj.get("current_mileage"),
            "deleted_at": obj.get("deleted_at"),
            "id": obj.get("id"),
            "model": obj.get("model"),
            "name": obj.get("name"),
            "owner": VehicleOwner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "plate_number": obj.get("plate_number"),
            "status": obj.get("status"),
            "technician_ids": obj.get("technician_ids"),
            "updated_at": obj.get("updated_at"),
            "utilization_percent": obj.get("utilization_percent"),
            "vehicle_type": obj.get("vehicle_type"),
            "year": obj.get("year")
        })
        return _obj


